services:
  app:
    stdin_open: true
    tty: true
    image: adguard/adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "5000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    environment:
      ALLOWED_HOSTS: "127.0.0.1,localhost"

